### ISSUE TITLE
Advise maintainers to add a mention of fledge usage with docs to fledge, in their CONTRIBUTING guide

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#123]
It says

```

<!-- NEWS.md is maintained by https://cynkra.github.io/fledge, do not edit -->
```

Should it be more precise to explain _when_ you can refactor/tweak the README? Or to point to some part of the docs explaining that?

**Comment by krlmlr** [comment]
The "do not edit" is picked up by RStudio.

The maintainer is free to edit `NEWS.md` at any time, FWIW. The restrictions apply only if you care about the messages ending up in the Git tag, which may be now less important than it used to be.

The maintainer will know that they are using fledge and that the message does not apply to them. Can we document this clearly in the docs and leave the message unchanged? Otherwise contributors might think that for some reason this caveat doesn't apply to them.

**Comment by maelle** [comment]
> The restrictions apply only if you care about the messages ending up in the Git tag, which may be now less important than it used to be.

Why? But good to know!

I now understand the arguments.

**Comment by maelle** [comment]
I'll let this open and rephrase the title, for a small docs item.

**Comment by maelle** [comment]
The remark could go with the installation instructions, it's part of "setup".

**Comment by krlmlr** [comment]
In the past I used to create a new release by copying the contents of the annotated tag in the GitHub web UI. Now this part is automated (in #27 at least) so it's less of an issue -- only if you really rely on the correctness of the annotated tags for dev versions.
