### ISSUE TITLE
Split `pre_release()`

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#658]
- `pre_release()` becomes `cran_prepare()` and `cran_commit()`
- `release()` becomes `cran_submit()`
- `post_release()` becomes `cran_record()`

`cran_prepare()` should be easy to undo (in particular, no pushes), `cran_commit()` marks the point of no return for the repository.

**Comment by maelle** [comment]
related: #251

**Comment by maelle** [comment]
also: #96

**Comment by maelle** [comment]
I'm wondering whether there could be a push, but with a throwaway branch name (a random name). :thinking:

**Comment by maelle** [comment]
the branch name could be the target branch name + something based on the current date and time, and it'd be renamed by `cran_commit()`.

**Comment by maelle** [comment]
Did I get this right :sweat_smile: 

The more I look into this the more I am wondering
- **why a release *PR*?** as opposed to a release *issue*.
- what do you hope to see in the diff of a release *PR*? only DESCRIPTION and NEWS.md + cran-comments.md changes?  

## `cran_prepare()`
- create release branch with a suffix (`as.numeric(Sys.time())`) = "draft"
- git/GitHub checks
- which "guessing" if needed
- on main branch: `update_news(which = which)`, `commit_version()`. NOT `bump_version_to_dev_with_force()`
- on release branch "draft": `update_cran_comments()`, `edit_news()`, `edit_cran_comments()`, list action items (fix them so they refer to `cran_commit()` not `release()`)

The user would do all the checks etc locally, and if needed
- hum `unbump_version()`, make commits to main branch (depending on finding from the checks)
- re-run `cran_prepare()`.

That said I am getting a bit confused. **Why not run all the changes from a branch called say `cran-1.1.0-draft-123`, then if all good merge this into main, then create the actual release branch since all will have been checked?**

## `cran_commit()`
- GitHub PAT checks here?
- on main, `bump_version(which = "dev")`
- push main
- rename release branch without the suffix
- open PR
